title:            "@banj"
url:              http://bdonald.com
permalink:        pretty
highlighter:      pygments
google_analytics: UA-49821100-1
timezone:         America/New_York
sass:
  sass_dir: assets
  style: :compressed
gems:
  - jemoji
  - jekyll-mentions
