title:            banj - @banjerbee || @banj
url:              http://www.naturevsindustry.com
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-49821100-1
timezone:         America/New_York
paginate: 5
gems:
  - jemoji
  - jekyll-mentions
