title:            banj - @banjerbee || @banj
url:              http://www.naturevsindustry.com
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: 
timezone:         
paginate: 5
gems:
  - jemoji
  - jekyll-mentions
